ALTER TABLE "RiskPolicy" ADD COLUMN IF NOT EXISTS "maxAssetClassExposure" DOUBLE PRECISION DEFAULT 35;
ALTER TABLE "RiskPolicy" ADD COLUMN IF NOT EXISTS "minLiquidityCoverage" DOUBLE PRECISION DEFAULT 1.5;
ALTER TABLE "RiskPolicy" ADD COLUMN IF NOT EXISTS "targetLiquidityBuffer" DOUBLE PRECISION DEFAULT 0.15;
ALTER TABLE "RiskPolicy" ADD COLUMN IF NOT EXISTS "maxPortfolioLeverage" DOUBLE PRECISION DEFAULT 0.5;
