ALTER TABLE "Fund" ADD COLUMN IF NOT EXISTS "strategy" TEXT DEFAULT 'Generalist';
ALTER TABLE "Fund" ADD COLUMN IF NOT EXISTS "sector" TEXT;
ALTER TABLE "Fund" ADD COLUMN IF NOT EXISTS "baseCurrency" TEXT DEFAULT 'USD';
ALTER TABLE "Fund" ADD COLUMN IF NOT EXISTS "leverage" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Fund" ADD COLUMN IF NOT EXISTS "preferredReturn" DOUBLE PRECISION DEFAULT 0.08;
CREATE INDEX IF NOT EXISTS "Fund_strategy_idx" ON "Fund"("strategy");
